HEADER_X = 20
HEADER_Y = 35

RESULTS_X = 20
RESULTS_Y = 75
RESULT_SPACING = 30
DETAIL_SPACING = 25

CONTROLS_X = 20
CONTROLS_BOTTOM_MARGIN = 20

BOX_THICKNESS = 2

HEADER_FONT_SCALE = 0.8
RESULT_FONT_SCALE = 0.6
DETAIL_FONT_SCALE = 0.5
CONTROL_FONT_SCALE = 0.5
